/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as DetailsUserIdImport } from './routes/details.$userId'
import { Route as LayoutRegisterImport } from './routes/_layout/register'
import { Route as LayoutLoginImport } from './routes/_layout/login'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const DetailsUserIdRoute = DetailsUserIdImport.update({
  path: '/details/$userId',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRegisterRoute = LayoutRegisterImport.update({
  path: '/register',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginRoute = LayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/login': {
      preLoaderRoute: typeof LayoutLoginImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/register': {
      preLoaderRoute: typeof LayoutRegisterImport
      parentRoute: typeof LayoutImport
    }
    '/details/$userId': {
      preLoaderRoute: typeof DetailsUserIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([LayoutLoginRoute, LayoutRegisterRoute]),
  DetailsUserIdRoute,
])

/* prettier-ignore-end */
