/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutRegisterImport } from './routes/_layout/register'
import { Route as LayoutLoginImport } from './routes/_layout/login'
import { Route as AuthUserUsernameImport } from './routes/_auth/user.$username'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRegisterRoute = LayoutRegisterImport.update({
  path: '/register',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginRoute = LayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthUserUsernameRoute = AuthUserUsernameImport.update({
  path: '/user/$username',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/login': {
      preLoaderRoute: typeof LayoutLoginImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/register': {
      preLoaderRoute: typeof LayoutRegisterImport
      parentRoute: typeof LayoutImport
    }
    '/_auth/user/$username': {
      preLoaderRoute: typeof AuthUserUsernameImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([AuthUserUsernameRoute]),
  LayoutRoute.addChildren([LayoutLoginRoute, LayoutRegisterRoute]),
])

/* prettier-ignore-end */
