/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutRegisterImport } from './routes/_layout/register'
import { Route as LayoutLoginImport } from './routes/_layout/login'
import { Route as AuthDetailsUsernameImport } from './routes/_auth/details.$username'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRegisterRoute = LayoutRegisterImport.update({
  path: '/register',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginRoute = LayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthDetailsUsernameRoute = AuthDetailsUsernameImport.update({
  path: '/details/$username',
  getParentRoute: () => AuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/login': {
      preLoaderRoute: typeof LayoutLoginImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/register': {
      preLoaderRoute: typeof LayoutRegisterImport
      parentRoute: typeof LayoutImport
    }
    '/_auth/details/$username': {
      preLoaderRoute: typeof AuthDetailsUsernameImport
      parentRoute: typeof AuthRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRouteRoute.addChildren([AuthDetailsUsernameRoute]),
  LayoutRoute.addChildren([LayoutLoginRoute, LayoutRegisterRoute]),
])

/* prettier-ignore-end */
